Flexy\DatabaseConfigBundle\Entity\Extension:
  type: entity
  table: container_extension
  fields:
    id:
        type: integer
        id: true
        generator:
            strategy: AUTO
    name:
        type: string
        length: 255
  lifecycleCallbacks: {  }
  repositoryClass: Flexy\DatabaseConfigBundle\Entity\ExtensionRepository
  oneToMany:
      configs:
        targetEntity: Flexy\DatabaseConfigBundle\Entity\Config
        mappedBy: extension
        cascade: [ persist, remove ]
        orphanRemoval: true