Unifik\DatabaseConfigBundle\Entity\Parameter:
  type: entity
  table: container_parameter
  fields:
      id:
          type: integer
          id: true
          generator:
              strategy: AUTO
      name:
          type: string
          length: 255
      value:
          type: string
          length: 255
  lifecycleCallbacks: {  }
