# Configurator
flexy_configurator:
    pattern:  /configurator
    defaults: { _controller: "FlexyDatabaseConfigBundle:Configurator:index" }
    options: { do_not_remove: true }

flexy_configurator_edit:
    pattern:  /configurator/{bundleName}
    defaults: { _controller: "FlexyDatabaseConfigBundle:Configurator:edit" }
    options: { do_not_remove: true }