# Configurator
unifik_configurator:
    pattern:  /configurator
    defaults: { _controller: "UnifikDatabaseConfigBundle:Configurator:index" }
    options: { do_not_remove: true }

unifik_configurator_edit:
    pattern:  /configurator/{bundleName}
    defaults: { _controller: "UnifikDatabaseConfigBundle:Configurator:edit" }
    options: { do_not_remove: true }