parameters:
    flexy_database_config.container_invalidator.class: Flexy\DatabaseConfigBundle\Lib\ContainerInvalidator

services:
    flexy_database_config.container_invalidator:
        class: %flexy_database_config.container_invalidator.class%
        arguments: [ @kernel ]